[package]
name = "PolarBear"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", default-features = false, features = ["std"] }
artic_tls = { path = "src/artic_tls" }
#native-tls = "0.2"